const nissanCars = [
  {
    id: 1,
    model: "Nissan Versa Sense",
    type: "Sedan",
    price: 334900,
    year: 2026,
    engine: "1.6 L, 4 cilindros",
    fuel: "18.5 km/l combinado",
    transmission: "Manual de 5 velocidades",
    seats: 5,
    color: "Blanco perlado",
    image: "https://tse2.mm.bing.net/th/id/OIP.QvuqL0WsJNVfsCpZYPFzcgHaDx?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    description: "Sedan compacto para ciudad, con buen espacio interior, consumo eficiente y manejo sencillo.",
    features: ["Pantalla de 7 pulgadas", "Camara de reversa", "6 bolsas de aire", "Frenos ABS"]
  },
  {
    id: 2,
    model: "Nissan Versa Advance",
    type: "Sedan",
    price: 382900,
    year: 2026,
    engine: "1.6 L, 4 cilindros",
    fuel: "18.2 km/l combinado",
    transmission: "CVT",
    seats: 5,
    color: "Gris oxford",
    image: "https://cimbaju.com.br/wp-content/uploads/2024/05/Nissan-Versa-Sense-1.6-AT-380x238.webp",
    description: "Version equilibrada con transmision automatica CVT, conectividad y asistencias para uso diario.",
    features: ["Apple CarPlay", "Android Auto", "Llave inteligente", "Alerta de punto ciego"]
  },
  {
    id: 3,
    model: "Nissan Sentra Advance",
    type: "Sedan",
    price: 453900,
    year: 2026,
    engine: "2.0 L, 4 cilindros",
    fuel: "17.4 km/l combinado",
    transmission: "CVT",
    seats: 5,
    color: "Azul electrico",
    image: "https://motor-fan.jp/wp-content/uploads/sites/4/2025/03/Nissan-Sentra_001.jpg",
    description: "Sedan amplio con cabina comoda, buena respuesta y tecnologia de seguridad para carretera.",
    features: ["NissanConnect", "Monitor inteligente", "Control crucero", "Rines de aluminio"]
  },
  {
    id: 4,
    model: "Nissan Sentra Exclusive",
    type: "Sedan",
    price: 524900,
    year: 2026,
    engine: "2.0 L, 4 cilindros",
    fuel: "17.1 km/l combinado",
    transmission: "CVT",
    seats: 5,
    color: "Rojo escarlata",
    image: "https://tse1.mm.bing.net/th/id/OIP.4d2f5kjA9JrfCZwgfQXgPwHaD5?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    description: "La version mas equipada del Sentra, con acabados superiores y asistencias inteligentes.",
    features: ["Quemacocos", "Asientos en piel", "Audio premium", "Frenado inteligente"]
  },
  {
    id: 5,
    model: "Nissan Altima SR",
    type: "Sedan",
    price: 721900,
    year: 2026,
    engine: "2.5 L, 4 cilindros",
    fuel: "15.9 km/l combinado",
    transmission: "CVT",
    seats: 5,
    color: "Negro obsidiana",
    image: "https://tse2.mm.bing.net/th/id/OIP.POOuHLo5y-8t6Zj9r-roxQHaE8?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    description: "Sedan mediano con presencia deportiva, manejo suave y gran comodidad para viajes largos.",
    features: ["Modo Sport", "Pantalla tactil", "Sensores delanteros", "Faros LED"]
  },
  {
    id: 6,
    model: "Nissan Altima Platinum",
    type: "Sedan",
    price: 815900,
    year: 2026,
    engine: "2.5 L, 4 cilindros",
    fuel: "15.5 km/l combinado",
    transmission: "CVT",
    seats: 5,
    color: "Plata brillante",
    image: "https://tse4.mm.bing.net/th/id/OIP.02Yj_6tbdOjwfIKuPwwCCwHaDt?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    description: "Altima con enfoque premium, cabina silenciosa, asistencia avanzada y acabados elegantes.",
    features: ["Asientos calefactables", "Camara 360", "ProPILOT Assist", "Audio Bose"]
  },
  {
    id: 7,
    model: "Nissan March Sense",
    type: "Sedan",
    price: 289900,
    year: 2026,
    engine: "1.6 L, 4 cilindros",
    fuel: "17.8 km/l combinado",
    transmission: "Manual de 5 velocidades",
    seats: 5,
    color: "Naranja cobre",
    image: "https://tse4.mm.bing.net/th/id/OIP.7jhiDBM9b6jxmIvhgzXHvAHaEC?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    description: "Auto urbano facil de estacionar, ideal para moverse en ciudad con bajo costo de uso.",
    features: ["Aire acondicionado", "Bluetooth", "Cristales electricos", "Bolsas de aire frontales"]
  },
  {
    id: 8,
    model: "Nissan March Advance",
    type: "Sedan",
    price: 326900,
    year: 2026,
    engine: "1.6 L, 4 cilindros",
    fuel: "17.6 km/l combinado",
    transmission: "Automatica de 4 velocidades",
    seats: 5,
    color: "Rojo metalico",
    image: "https://tse3.mm.bing.net/th/id/OIP.BQmcIj5gfOwYuoo7_bzzOwHaE8?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    description: "Version automatica practica, pensada para traslados diarios con comodidad extra.",
    features: ["Pantalla central", "Camara trasera", "Controles al volante", "Rines bitono"]
  },
  {
    id: 9,
    model: "Nissan Kicks Sense",
    type: "SUV",
    price: 432900,
    year: 2026,
    engine: "1.6 L, 4 cilindros",
    fuel: "17.7 km/l combinado",
    transmission: "CVT",
    seats: 5,
    color: "Gris volcanico",
    image: "https://tse1.mm.bing.net/th/id/OIP.qvCZ48t4eNUBW0UbgdagDgHaD5?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    description: "SUV compacta con posicion de manejo alta, buena eficiencia y diseno moderno.",
    features: ["Pantalla de 8 pulgadas", "Control dinamico", "Asistente de arranque", "Faros automaticos"]
  },
  {
    id: 10,
    model: "Nissan Kicks Exclusive",
    type: "SUV",
    price: 519900,
    year: 2026,
    engine: "1.6 L, 4 cilindros",
    fuel: "17.2 km/l combinado",
    transmission: "CVT",
    seats: 5,
    color: "Blanco con techo negro",
    image: "https://autoenaccion.com.ar/wp-content/uploads/2024/02/nissan-kicks-exclusive-prueba-delantera.jpg",
    description: "SUV compacta equipada con tecnologia de asistencia y detalles exteriores bitono.",
    features: ["Camara 360", "Alerta de trafico cruzado", "Asientos en piel", "Luces LED"]
  },
  {
    id: 11,
    model: "Nissan X-Trail Advance",
    type: "SUV",
    price: 679900,
    year: 2026,
    engine: "2.5 L, 4 cilindros",
    fuel: "15.2 km/l combinado",
    transmission: "CVT",
    seats: 5,
    color: "Verde jade",
    image: "https://img.freepik.com/premium-photo/nissan-nissan-gtr-nissan-car-issan-gtr-wallpaper-4k-nissan-gtr-r35-nissan-gtr-r34_1097779-3808.jpg?w=2000",
    description: "SUV familiar con amplio espacio, cajuela versatil y conduccion comoda en ciudad o carretera.",
    features: ["Tres modos de manejo", "Porton electrico", "Climatizador dual", "Sensores traseros"]
  },
  {
    id: 12,
    model: "Nissan X-Trail e-POWER",
    type: "Electrico",
    price: 812900,
    year: 2026,
    engine: "Sistema e-POWER",
    fuel: "19.8 km/l combinado",
    transmission: "Electrica",
    seats: 5,
    color: "Azul titanio",
    image: "https://www.nissan.com.mx/content/dam/Nissan/mexico/assets/xtrail_e_power/my25/vlp/accesorios/nissan-2025-xtrail_platinum_3_row-azul_imperial-negro-exterior-accesorios_header-d.jpg",
    description: "SUV electrificada con manejo electrico y motor a gasolina como generador de energia.",
    features: ["e-Pedal Step", "ProPILOT Assist", "Pantalla digital", "Camara 360"]
  },
  {
    id: 13,
    model: "Nissan Pathfinder Advance",
    type: "SUV",
    price: 1049900,
    year: 2026,
    engine: "3.5 L V6",
    fuel: "11.6 km/l combinado",
    transmission: "Automatica de 9 velocidades",
    seats: 8,
    color: "Gris titanio",
    image: "https://xehay.vn/uploads/images/2025/11/02/xehay_Pathfinder%202026_141125_1.jpg",
    description: "SUV grande para familia, con tres filas, gran capacidad de carga y motor potente.",
    features: ["8 asientos", "Remolque avanzado", "Pantalla de 9 pulgadas", "Alerta de colision"]
  },
  {
    id: 14,
    model: "Nissan Pathfinder Platinum",
    type: "SUV",
    price: 1239900,
    year: 2026,
    engine: "3.5 L V6",
    fuel: "11.2 km/l combinado",
    transmission: "Automatica de 9 velocidades",
    seats: 8,
    color: "Blanco perla",
    image: "https://images.dealer.com/ddc/vehicles/2026/Nissan/Pathfinder/SUV/trim_Platinum_477e75/color/Everest%20White%20Pearl%20Tricoat-QBE-227%2C230%2C235-640-en_US.jpg?impolicy=resize&w=1024",
    description: "Pathfinder con acabados premium, asistencia completa y confort para todos los pasajeros.",
    features: ["Asientos ventilados", "Audio Bose", "Techo panoramico", "Navegacion"]
  },
  {
    id: 15,
    model: "Nissan Armada SL",
    type: "SUV",
    price: 1429900,
    year: 2026,
    engine: "5.6 L V8",
    fuel: "8.9 km/l combinado",
    transmission: "Automatica de 7 velocidades",
    seats: 8,
    color: "Negro diamante",
    image: "https://tse1.mm.bing.net/th/id/OIP.hfU6TRsk5C7cOZVZgNrr-AHaDV?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    description: "SUV grande de alto desempeno, con mucha fuerza, lujo y presencia en carretera.",
    features: ["Traccion 4x4", "Remolque pesado", "Piel premium", "Control de descenso"]
  },
  {
    id: 16,
    model: "Nissan Murano Platinum",
    type: "SUV",
    price: 945900,
    year: 2026,
    engine: "3.5 L V6",
    fuel: "12.4 km/l combinado",
    transmission: "CVT",
    seats: 5,
    color: "Cobre sunset",
    image: "https://i.ytimg.com/vi/Ovc4u1QHJEw/maxresdefault.jpg",
    description: "SUV elegante con cabina refinada, manejo suave y diseno llamativo.",
    features: ["Techo panoramico", "Asientos Zero Gravity", "Audio Bose", "Camara 360"]
  },
  {
    id: 17,
    model: "Nissan Magnite Advance",
    type: "SUV",
    price: 379900,
    year: 2026,
    engine: "1.0 L turbo",
    fuel: "18.9 km/l combinado",
    transmission: "CVT",
    seats: 5,
    color: "Azul zafiro",
    image: "https://tse2.mm.bing.net/th/id/OIP.1Spx2g51AdZFjTFN0qmzTQHaE8?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    description: "SUV subcompacta con motor turbo, tamano practico y equipamiento atractivo.",
    features: ["Motor turbo", "Pantalla tactil", "Camara trasera", "Control de estabilidad"]
  },
  {
    id: 18,
    model: "Nissan Frontier S",
    type: "Pickup",
    price: 518900,
    year: 2026,
    engine: "2.5 L gasolina",
    fuel: "11.9 km/l combinado",
    transmission: "Manual de 6 velocidades",
    seats: 5,
    color: "Blanco solido",
    image:"https://tse1.mm.bing.net/th/id/OIP.ydU_aVNRonOyCjoYoFpxCAHaEK?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    description: "Pickup resistente para trabajo, con chasis fuerte y buena capacidad de carga.",
    features: ["Caja amplia", "Control de traccion", "Ganchos de carga", "Protector de caja"]
  },
  {
    id: 19,
    model: "Nissan Frontier Pro-4X",
    type: "Pickup",
    price: 789900,
    year: 2026,
    engine: "3.8 L V6",
    fuel: "10.5 km/l combinado",
    transmission: "Automatica de 9 velocidades",
    seats: 5,
    color: "Rojo lava",
    image: "https://dealerimages.dealereprocess.com/image/upload/v1697826814/1/nissan/2024_Frontier/Crew_Cab_ProX/4x2-crew-cab-pro-x-red-alert.png",
    description: "Pickup preparada para aventura, con traccion 4x4, protecciones y estilo deportivo.",
    features: ["Diferencial bloqueable", "Amortiguadores Bilstein", "Skid plates", "Camara off-road"]
  },
  {
    id: 20,
    model: "Nissan NP300 Chasis",
    type: "Pickup",
    price: 423900,
    year: 2026,
    engine: "2.5 L gasolina",
    fuel: "12.8 km/l combinado",
    transmission: "Manual de 6 velocidades",
    seats: 3,
    color: "Blanco comercial",
    image: "https://tse4.mm.bing.net/th/id/OIP.9LL523qcflvszCXdx5VlkgHaEK?r=0&pid=ImgDet&w=474&h=266&rs=1&o=7&rm=3",
    description: "Vehiculo de trabajo listo para adaptar caja seca, redilas o plataforma segun el negocio.",
    features: ["Chasis reforzado", "Gran capacidad de carga", "Cabina sencilla", "Bajo mantenimiento"]
  },
  {
    id: 21,
    model: "Nissan Titan Crew Cab",
    type: "Pickup",
    price: 1199900,
    year: 2026,
    engine: "5.6 L V8",
    fuel: "8.7 km/l combinado",
    transmission: "Automatica de 9 velocidades",
    seats: 5,
    color: "Gris acero",
    image: "https://tse3.mm.bing.net/th/id/OIP.P6QQhPiuXPbTLf3HzMqe8QHaEK?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    description: "Pickup grande con motor V8, alto nivel de fuerza y comodidad para viajes largos.",
    features: ["Motor V8", "Remolque avanzado", "Cabina amplia", "Asientos calefactables"]
  },
  {
    id: 22,
    model: "Nissan Z Sport",
    type: "Deportivo",
    price: 1299900,
    year: 2026,
    engine: "3.0 L V6 twin-turbo",
    fuel: "10.8 km/l combinado",
    transmission: "Manual de 6 velocidades",
    seats: 2,
    color: "Amarillo ikazuchi",
    image: "https://th.bing.com/th/id/OIP.W28PkmYff3jEMVQEyA0NZwHaEi?r=0&o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3",
    description: "Coupe deportivo con motor twin-turbo, traccion trasera y diseno inspirado en la historia Z.",
    features: ["Diferencial mecanico", "Modo Sport", "Tablero digital", "Frenos deportivos"]
  },
  {
    id: 23,
    model: "Nissan Z Performance",
    type: "Deportivo",
    price: 1519900,
    year: 2026,
    engine: "3.0 L V6 twin-turbo",
    fuel: "10.4 km/l combinado",
    transmission: "Automatica de 9 velocidades",
    seats: 2,
    color: "Azul seiran",
    image: "https://th.bing.com/th/id/OIP.Ua19ewwuTASC6lUtfGoz0QHaEK?r=0&o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3",
    description: "Version de alto desempeno del Nissan Z, con respuesta rapida y equipamiento deportivo.",
    features: ["Launch control", "Paletas al volante", "Frenos Akebono", "Audio Bose"]
  },
  {
    id: 24,
    model: "Nissan GT-R Premium",
    type: "Deportivo",
    price: 2899900,
    year: 2026,
    engine: "3.8 L V6 twin-turbo",
    fuel: "8.8 km/l combinado",
    transmission: "Doble embrague de 6 velocidades",
    seats: 4,
    color: "Plata super silver",
    image: "https://i.ytimg.com/vi/4zF7Byc4pUg/maxresdefault.jpg",
    description: "Superdeportivo con traccion integral, aceleracion contundente y herencia de pista.",
    features: ["AWD ATTESA", "Suspension adaptativa", "Frenos Brembo", "Telemetria"]
  },
  {
    id: 25,
    model: "Nissan Leaf SV Plus",
    type: "Electrico",
    price: 782900,
    year: 2026,
    engine: "Motor electrico",
    fuel: "Hasta 342 km de autonomia",
    transmission: "Electrica de una velocidad",
    seats: 5,
    color: "Blanco glacial",
    image: "https://tse4.mm.bing.net/th/id/OIP.2ARzcuA9uz0qm2lIuFabXQHaDx?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    description: "Hatchback electrico silencioso, eficiente y facil de cargar para uso diario.",
    features: ["Carga rapida", "e-Pedal", "NissanConnect EV", "Cero emisiones locales"]
  },
  {
    id: 26,
    model: "Nissan Ariya Engage",
    type: "Electrico",
    price: 1049900,
    year: 2026,
    engine: "Motor electrico",
    fuel: "Hasta 490 km de autonomia",
    transmission: "Electrica de una velocidad",
    seats: 5,
    color: "Cobre akatsuki",
    image: "https://tse2.mm.bing.net/th/id/OIP.u0GUr09xU8lspO6u-wRTvwHaC2?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    description: "SUV electrica con diseno futurista, cabina minimalista y autonomia para viajes.",
    features: ["Carga rapida DC", "Pantallas duales", "ProPILOT Assist", "Piso plano"]
  },
  {
    id: 27,
    model: "Nissan Ariya Platinum e-4ORCE",
    type: "Electrico",
    price: 1289900,
    year: 2026,
    engine: "Doble motor electrico",
    fuel: "Hasta 430 km de autonomia",
    transmission: "Electrica AWD",
    seats: 5,
    color: "Azul aurora",
    image:"https://tse4.mm.bing.net/th/id/OIP.sdFTtfHkvgYn5KzsbMP2sgHaEK?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    description: "Ariya con traccion electrica integral, mayor potencia y sensacion premium.",
    features: ["e-4ORCE AWD", "Techo panoramico", "Head-up display", "Asientos ventilados"]
  },
  {
    id: 28,
    model: "Nissan Urvan Panel",
    type: "Van",
    price: 632900,
    year: 2026,
    engine: "2.5 L diesel",
    fuel: "12.9 km/l combinado",
    transmission: "Manual de 6 velocidades",
    seats: 3,
    color: "Blanco comercial",
    image: "https://cdn2.hubspot.net/hubfs/1794060/autoshow/vehiculos/202001/nissan/urvan-panel/nissan-urvan-panel-estanda-01.jpg",
    description: "Van de carga para reparto, flotillas y negocios que necesitan espacio cerrado.",
    features: ["Area de carga amplia", "Puertas corredizas", "Piso resistente", "Aire acondicionado"]
  },
  {
    id: 29,
    model: "Nissan Urvan Pasajeros",
    type: "Van",
    price: 759900,
    year: 2026,
    engine: "2.5 L diesel",
    fuel: "12.3 km/l combinado",
    transmission: "Manual de 6 velocidades",
    seats: 15,
    color: "Plata metalico",
    image:"https://th.bing.com/th/id/OIP.56W4FPU7LOKKBr58joiDtQHaE8?r=0&o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3",
    description: "Van para transporte de pasajeros, escuela, turismo o empresa.",
    features: ["15 pasajeros", "Aire acondicionado trasero", "Escalon lateral", "Ventanas amplias"]
  },
  {
    id: 30,
    model: "Nissan Townstar EV",
    type: "Electrico",
    price: 689900,
    year: 2026,
    engine: "Motor electrico",
    fuel: "Hasta 300 km de autonomia",
    transmission: "Electrica de una velocidad",
    seats: 2,
    color: "Gris urbano",
    image: "https://th.bing.com/th/id/OIP.yjy1TzLfAi51oDkBWjoI8gHaEK?r=0&o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3",
    description: "Van electrica compacta para reparto urbano con bajo costo de operacion.",
    features: ["Carga rapida", "Espacio modular", "Camara trasera", "Cero emisiones locales"]
  }
];
